@startuml
'http://plantuml.com/skinparam.html
autonumber 1

participant Server
participant Database

[-> Server: POST
activate Server
    Server -> Database: insert
    Database --> Server
    alt succesfull case
        [<- Server: 201 Code 
    else 
        [<- Server: 400 Code 
    end
deactivate Server

@enduml